[[LOCAL_JOB]]
    execution retry delays = PT10S, 2*PT2M
    submission retry delays = PT10S, 2*PT2M
    execution time limit = PT5M

[[PBS]]
    inherit = root
    platform = pbs

    execution retry delays = PT10S, 2*PT2M
    submission retry delays = PT10S, 2*PT2M

    pre-script = """
        module use /g/data/xp65/public/modules/
        module load conda/analysis3
        source $CYLC_WORKFLOW_SHARE_DIR/venv/bin/activate
    """

    [[[directives]]]
        -P = {{ PROJECT }}
        -q = {{ QUEUE }}
        -l storage = {{ STORAGE }}
        -l jobfs = 128GB

[[TINY_JOB]]
    inherit = PBS
    execution time limit = PT20M

    [[[directives]]]
        -l ncpus = 2
        -l mem = 8GB

[[SMALL_JOB]]
    inherit = PBS
    execution time limit = PT1H

    [[[directives]]]
        -l ncpus = 4
        -l mem = 16GB

[[MEDIUM_JOB]]
    inherit = PBS
    execution time limit = PT8H

    [[[directives]]]
        -l ncpus = 8
        -l mem = 32GB

[[LARGE_JOB]]
    inherit = PBS
    execution time limit = PT8H

    [[[directives]]]
        -l ncpus = 16
        -l mem = 64GB

[[SMALL_COPYQ_JOB]]
    inherit = PBS
    execution time limit = PT10M

    [[[directives]]]
        -q = copyq
        -l ncpus = 1
        -l mem = 8GB

[[MEDIUM_COPYQ_JOB]]
    inherit = PBS
    execution time limit = PT10H

    [[[directives]]]
        -q = copyq
        -l ncpus = 1
        -l mem = 32GB
