[template variables]
PROJECT = "tm70"
QUEUE = "normalbw"
# Need hr22 for cylc module, vk83 for payu module, then wherever the data is
STORAGE = "gdata/hr22+gdata/vk83+gdata/xp65+gdata/tm70+scratch/tm70+gdata/p73+gdata/jq44"
REALMS = "atmosphere", "ice", "ocean"

# If not using the launch.suite.sh script need to specify the directory of the data
DATASET_DIR = "/PATH/TO/DATASET"

# Number of outputX to run at a time
RUNAHEAD_LIMIT = 12
# Limit to number of simulataneous PBS jobs
PBS_LIMIT = 12

# Delete the old netCDF files once the new ones are created
# Otherwise old netCDF files will be archived in
#   $DATASET_DIR/output???/$REALM/old_data_archive
DELETE_OLD_DATA = False

# The following options enable and control "scratch mode" which will only create
# and modify files in the designated directory i.e. don't change the original
# dataset and create new files on scratch for testing etc.
# Files will be written to $SCRATCH_DIR/$DATASET_NAME/outputX/...
# Enable or disable "scratch mode"
SCRATCH_MODE = False
# Root directory for scratch mode
# Data will be written to $SRATCH_DIR/$DATASET_NAME
SCRATCH_DIR = "/scratch/tm70/$USER/esm1p6_postprocessing"
