per_cell:
  - "CABLE SOIL TEMPERATURE LAYER 1 (K)"
  - "CABLE SOIL TEMPERATURE LAYER 2 (K)"
  - "CABLE SOIL TEMPERATURE LAYER 3 (K)"
  - "CABLE SOIL TEMPERATURE LAYER 4 (K)"
  - "CABLE SOIL TEMPERATURE LAYER 5 (K)"
  - "CABLE SOIL TEMPERATURE LAYER 6 (K)"
  - "CABLE SOIL MOISTURE LAYER    1"
  - "CABLE SOIL MOISTURE LAYER    2"
  - "CABLE SOIL MOISTURE LAYER    3"
  - "CABLE SOIL MOISTURE LAYER    4"
  - "CABLE SOIL MOISTURE LAYER    5"
  - "CABLE SOIL MOISTURE LAYER    6"
  - "CABLE SOIL FROZEN FRAC LAYER 1"
  - "CABLE SOIL FROZEN FRAC LAYER 2"
  - "CABLE SOIL FROZEN FRAC LAYER 3"
  - "CABLE SOIL FROZEN FRAC LAYER 4"
  - "CABLE SOIL FROZEN FRAC LAYER 5"
  - "CABLE SOIL FROZEN FRAC LAYER 6"
  - "SNOW DEPTH LAYER 1 (ON TILES)"
  - "SNOW DEPTH LAYER 2 (ON TILES)"
  - "SNOW DEPTH LAYER 3 (ON TILES)"
  - "SNOW MASS LAYER 1 (ON TILES)"
  - "SNOW MASS LAYER 2 (ON TILES)"
  - "SNOW MASS LAYER 3 (ON TILES)"
  - "SNOW TEMPERATURE LAYER 1 (ON TILES)"
  - "SNOW TEMPERATURE LAYER 2 (ON TILES)"
  - "SNOW TEMPERATURE LAYER 3 (ON TILES)"
  - "SNOW DENSITY LAYER 1 (ON TILES)"
  - "SNOW DENSITY LAYER 2 (ON TILES)"
  - "SNOW DENSITY LAYER 3 (ON TILES)"
  - "SNOW MEAN DENSITY (ON TILES)"
  - "SNOW AGE (ON TILES)"
  - "CANOPY WATER ON TILES  KG PER M2"
  - "SOIL RESPIRATION ON TILES (CASA-CNP)"
  - "PLANT RESPIRATION ON TILES (CASA)"
  - "NET PRIMARY PRODUCTIVITY (NPP)"

per_tile:
  - "CARBON POOL LABILE ON TILES"
  - "CARBON POOL PLANT - LEAF ON TILES"
  - "CARBON POOL PLANT - WOOD ON TILES"
  - "CARBON POOL PLANT - ROOT ON TILES"
  - "CARBON POOL LITTER - METB ON TILES"
  - "CARBON POOL LITTER - STR ON TILES"
  - "CARBON POOL LITTER - CWD ON TILES"
  - "CARBON POOL SOIL - MIC ON TILES"
  - "CARBON POOL SOIL - SLOW ON TILES"
  - "CARBON POOL SOIL - PASS ON TILES"
  - "NITROGEN POOL PLANT - LEAF ON TILES"
  - "NITROGEN POOL PLANT - WOOD ON TILES"
  - "NITROGEN POOL PLANT - ROOT ON TILES"
  - "NITROGEN POOL LITTER - METB ON TILES"
  - "NITROGEN POOL LITTER - STR ON TILES"
  - "NITROGEN POOL LITTER - CWD ON TILES"
  - "NITROGEN POOL SOIL - MIC ON TILES"
  - "NITROGEN POOL SOIL - SLOW ON TILES"
  - "NITROGEN POOL SOIL - PASS ON TILES"
  - "NITROGEN POOL SOIL MINIMUM (TILES)"
  - "PHOSPHORUS POOL PLANT - LEAF (TILES)"
  - "PHOSPHORUS POOL PLANT - WOOD (TILES)"
  - "PHOSPHORUS POOL PLANT - ROOT (TILES)"
  - "PHOSPHORUS POOL LITTER- METB (TILES)"
  - "PHOSPHORUS POOL LITTER - STR (TILES)"
  - "PHOSPHORUS POOL LITTER - CWD (TILES)"
  - "PHOSPHORUS POOL SOIL - MIC (TILES)"
  - "PHOSPHORUS POOL SOIL - SLOW (TILES)"
  - "PHOSPHORUS POOL SOIL - PASS (TILES)"
  - "PHOSPHORUS POOL SOIL LABILE (TILES)"
  - "PHOSPHORUS POOL SOIL SORB ON TILES"
  - "PHOSPHORUS POOL SOIL OCC ON TILES"
  - "LEAF AREA INDEX (CASA-CNP GLAI)"

vegetation_map:
  10: [6, 7, 9]
search_radius: 2
latitude_band: 8
minimum_points: 1
