[template variables]
PROJECT = "tm70"
QUEUE = "normalbw"
STORAGE = "gdata/tm70+scratch/tm70"
REALMS = "atmosphere", "ice", "ocean"
DATASET_DIR = "/scratch/tm70/jt4085/esm16_examples/1pcC02-01"
# Number of outputX to run at a time
# 1 for testing, increase to say 20?
RUNAHEAD_LIMIT = 1
# Limit to number of simulataneous PBS jobs
# 1 for testing, increase to, say, 10?
PBS_LIMIT = 1
