# https://metomi.github.io/rose/doc/html/api/built-in/rose_prune.html
meta=rose_prune
mode=rose_prune

[prune]
# archive (e.g. "tar") local log files from cycles a number of cycles before
# the current cycle
# i.e. gzip cylc-run/<workflow>/<log>/<job>/<cycle>
archive-logs-at=$ARCHIVE_DELAY
